### ISSUE TITLE
Office 365 automation on Dev Box

### ISSUE THREAD

**Issue by ariellourenco** [microsoft/devcenter-examples#13]
Hi there,

This is more like a question than an issue to be honest. I would like to automate the installation of Office 365 on my Dev Box in a way that only the required apps would be installed in order to optimize Disk space. For this mission I am using `OfficeDeploymentTool` which I am installing via `winget`. I have a sort of draft powershelgl script that I would like to run as part of my customization but not sure if this is the best way to achieve what I want.

```yaml
    - resource: PSDscResources/Script
      id: Microsoft.Office
      directives:
        description: Install Microsoft Office 365
      settings:
        SetScript: |
          $GITHUB_BASE_URL = "https://raw.githubusercontent.com/company/projectsettings/main"

          # Install Office Deployment Tool
          # The OfficeDeploymentTool will be installed in the "C:\Program Files\OfficeDeploymentTool"
          winget install --id=Microsoft.OfficeDeploymentTool  -e

          # Navigate to the Office Deployment Tool directory
          cd "C:\Program Files\OfficeDeploymentTool"

          Write-Host "Fetching configuration files..."
          (Invoke-webrequest -URI $GITHUB_BASE_URL/office/configuration.xml).Content > deployment.xml

          # Execute the setup.exe with the downloaded configuration file
          .\setup.exe /configure deployment.xml

          Write-ScreenInfo -Message 'Waiting for Office 365 to complete installation' -NoNewline
        GetScript: return $false
        TestScript: return $false
``

Any help would be much appreciated.

**Comment by ariellourenco** [comment]
I have improved the WinGet Configuration file for install Office. However, the way I have done it does not take into account if the target machine has an older version of the Office or even whether the user wants to update his current installation. It may be better to remove all the verifications on `TestScript` and rely on the Office installer to have the indepotency aspect of `PSDscResources/Script`. Anyway, I am sharing it here in the hope someone could review it and spot some improvements or better ideas.

```yaml
# ymal-language-server: $schema=https://aka.ms/configuration-dsc-schema/0.2
properties:
  configurationVersion: 0.2.0
  assertions:
    - resource: Microsoft.Windows.Developer/OsVersion
      id: OsVersion
      directives:
        description: Minimum OS version requirement
        allowPrerelease: true
      settings:
        MinVersion: "10.0.22621.2338"
  resources:
    ### Download and extract the Office Deployment Tool to C:\Program Files\OfficeDeploymentTool
    - resource: Microsoft.WinGet.DSC/WinGetPackage
      id: OfficeDeploymentTool
      directives:
        description: Download and extract the Office Deployment Tool
        allowPrerelease: true
      settings:
        id: Microsoft.OfficeDeploymentTool
    - resource: PSDscResources/Script
      dependsOn:
        - OfficeDeploymentTool
      directives:
        description: Install Microsoft 365 Apps
        allowPrerelease: true
      settings:
        GetScript: |
          # Find the registry key for the Office 365 product
          $key = (Get-Item -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*" |
            Where-Object { $_.GetValue("DisplayName") -like "Office*" })

          return $null -ne $key
        TestScript: |
          # Find the registry key for the Office 365 product
          $key = (Get-Item -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\*" |
            Where-Object { $_.GetValue("DisplayName") -like "Office*" })

          return $null -ne $key
        SetScript: |
          $url = "https://raw.githubusercontent.com/ariellourenco/dotfiles/main/windows/office/configuration-Office365-x64.xml"
          $filePath = Join-Path -Path $env:PROGRAMFILES -ChildPath "OfficeDeploymentTool"
          $fileName = Split-Path -Path $url -Leaf

          if (-not (Test-Path -Path $filePath)) {
            Write-Error "The directory $filePath does not exist. Please, ensure that the Office Deployment Tool is installed."
          }

          # Download the file from the URL, overwriting if it exists
          Invoke-WebRequest -Uri $url -OutFile "$filePath/$fileName"
          Start-Sleep -Seconds 5

          # Execute ODT to install Office 365
          Start-Process -FilePath "$filePath\setup.exe" -WorkingDirectory $filePath -ArgumentList "/configure $fileName" -Wait
```
